### ISSUE TITLE
Class 'DenisKisel\Obfuscator\ServiceProvider' not found

### ISSUE THREAD

**Issue by monsieur-ricky** [denis-kisel/laravel-obfuscator#2]
I followed all the instructions and when i try to execute my app i get the following error:

> [2019-04-04 21:42:14] local.ERROR: Class 'DenisKisel\Obfuscator\ServiceProvider' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'DenisKisel\\Obfuscator\\ServiceProvider' not found at /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208)
> [stacktrace]
> #0 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider('DenisKisel\\\\Obfu...')
> #1 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest(Array)
> #2 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\\Foundation\\ProviderRepository->load(Array)
> #3 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
> #4 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(211): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
> #5 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
> #6 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
> #7 /srv/app/cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
> #8 /srv/app/cms/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
> #9 {main}
> "} 

What am i missing here?

**Comment by NeoMarine** [comment]
Under config/app.php 'providers' add this line:

**DenisKisel\Obfuscator\ObfuscatorServiceProvider::class,**

I believe this was a typo as the docs say DenisKisel\Obfuscator\ServiceProvider::class which is wrong

**Comment by monsieur-ricky** [comment]
@NeoMarine yep, thats it! :)

The documentation installation steps should be updated to the correct class.

**Comment by denis-kisel** [comment]
Thanks for issue and resolve!) Documentation is updated.
